# General configuration
target_fs: 128
band: [1, 9]
plot_seconds: 30
plot_steps: False
plot_Envelope_Checks: False

# Directory info
base_dir: "C:/Users/lilou/OneDrive/Documenten/thesis"

data_dir: "Data/EEGData"
stim_dir: "Data/stimuli"
PP_dir: "Data/preprocessed"
Env_dir: "Data/envelopes"

# Subjects to process
subjects:
  - S1
  # - S2
  # - S3
